/*
# Add lampiran (attachments) to Surat Masuk, Surat Keluar & Agenda Pimpinan

## Summary
Adds a `lampiran` column (jsonb array of attachment metadata) to the three
record tables, plus a private Supabase Storage bucket to hold the actual
scanned files (PDF or photo of the original letter).

## New column
- `lampiran` jsonb NOT NULL DEFAULT '[]' on surat_masuk, surat_keluar,
  agenda_pimpinan. Each element looks like:
  { "path": "surat-masuk/172...-abc.pdf", "name": "Surat asli.pdf",
    "type": "application/pdf", "size": 245678 }
  `path` is the object path inside the `lampiran-surat` storage bucket.
  The actual file bytes live in Storage, not in this column — only
  metadata is stored here so the UI can list/open/delete attachments.

## New storage bucket
- `lampiran-surat` — PRIVATE bucket (public = false). Files are only
  reachable via short-lived signed URLs generated by the app for
  authenticated users, not via a permanent public link. This matches the
  "family/office shares data, but it's still official correspondence"
  sensitivity of the app.

## Security (RLS)
- Same "shared data" model as the rest of the app (see the original
  disposisi tables migration): any authenticated user can read, upload,
  update, and delete objects in this bucket. No per-user isolation,
  because everyone using the app is expected to see all records.
- Anonymous/unauthenticated access is blocked.
*/

-- ===== lampiran columns =====
ALTER TABLE surat_masuk ADD COLUMN IF NOT EXISTS lampiran jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE surat_keluar ADD COLUMN IF NOT EXISTS lampiran jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE agenda_pimpinan ADD COLUMN IF NOT EXISTS lampiran jsonb NOT NULL DEFAULT '[]'::jsonb;

-- ===== storage bucket =====
INSERT INTO storage.buckets (id, name, public)
VALUES ('lampiran-surat', 'lampiran-surat', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "family_select_lampiran_surat" ON storage.objects;
CREATE POLICY "family_select_lampiran_surat"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'lampiran-surat');

DROP POLICY IF EXISTS "family_insert_lampiran_surat" ON storage.objects;
CREATE POLICY "family_insert_lampiran_surat"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'lampiran-surat');

DROP POLICY IF EXISTS "family_update_lampiran_surat" ON storage.objects;
CREATE POLICY "family_update_lampiran_surat"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'lampiran-surat')
  WITH CHECK (bucket_id = 'lampiran-surat');

DROP POLICY IF EXISTS "family_delete_lampiran_surat" ON storage.objects;
CREATE POLICY "family_delete_lampiran_surat"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'lampiran-surat');
